export default [
  {
    id: 1,
    img: require("../../images/profil-photo.png"),
    rating: "5.0",
    scope: 6,
    country: "USA",
    author: "Life lessons with Katie Zaferes",
    price: 136,
    openSpots: 0,
  },
  {
    id: 2,
    img: require("../../images/wedding-photography 1.png"),
    rating: "5.0",
    scope: 30,
    country: "USA",
    author: "Learn wedding photography",
    price: 125,
  },
  {
    id: 3,
    img: require("../../images/mountain-bike.png"),
    rating: "4.8",
    scope: 2,
    country: "USA",
    author: "Group Mountain Biking",
    price: 50,
  },
];
